### ISSUE TITLE
how to test only one cell?

### ISSUE THREAD

**Issue by IamMegatron2025** [cangermueller/deepcpg#10]
Hello, if I train model use several cells like BS27_1_SER, BS27_3_SER, BS27_5_SER, BS27_6_SER and BS27_8_SER. Then when I test this pretained model, it seems that I must provide this five cell tsv files. So if I want test only one cell tsv file, how should I do?
can you give some advises?
thank you very much~
look forward to your reply!

**Comment by cangermueller** [comment]
The trained DeepCpG model makes predictions for all cells that were used for training. Why don't you simply select the cell in which you are interested in from the output of `dcpg_eval.py`?
