### ISSUE TITLE
Fine tuning joint model doesn't seem to work.

### ISSUE THREAD

**Issue by Bonder-MJ** [cangermueller/deepcpg#12]
Is it possible to use --fine_tune on a joint model?

I tried to follow the Ipython example for retraining and replaced toe --cpg_model with --joint_model but when it tries to load the previous model I get an null pointer exception. Also when trying to give it the model separately by using --model_files this is not solved. In this case it has issues with not matching samples between the model and the new training data.

**Comment by cangermueller** [comment]
Sorry for the the late reply: I am quite busy with my new job ;-). Did you solve the issue? --fine_tune should also work for joint models.

**Comment by Bonder-MJ** [comment]
I  used another approach. I didn't manage to fine tine the joint model.
I get it ;-) Thanks for the reply!
