### ISSUE TITLE
ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.

### ISSUE THREAD

**Issue by AgentLjc** [cangermueller/deepcpg#13]
Hi,
Thanks for your software.After creating data as test,there is an issue when i execute
`dcpg_train.py ./data/c1_000000-001000.h5 --val_files ./data/c13_000000-001000.h5 --cpg_model RnnL1 --out_dir ./models/cpg --nb_epoch 1 --nb_train_sample 1000 --nb_val_sample 1000`
Here is the traceback:
Traceback (most recent call last):
  File "/home/ljc/down/deepcpg-keras2/scripts/dcpg_train.py", line 832, in <module>
    app.run(sys.argv)
  File "/home/ljc/down/deepcpg-keras2/scripts/dcpg_train.py", line 194, in run
    return self.main(name, opts)
  File "/home/ljc/down/deepcpg-keras2/scripts/dcpg_train.py", line 802, in main
    verbose=0)
  File "/home/ljc/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/ljc/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2082, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ljc/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/ljc/anaconda3/lib/python3.6/site-packages/keras/callbacks.py", line 751, in on_epoch_end
    raise ValueError('If printing histograms, validation_data must be '
ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.

Could you plz help me?Thanks a lot.

**Comment by cangermueller** [comment]
Which Keras version are you using? It should work with keras=2.0.2. Let me know if it does not work for any Keras version > 2.0.2.

**Comment by AgentLjc** [comment]
i use keras2.0.8.

**Comment by AgentLjc** [comment]
Thanks for reply ,i'm using keras 2.0.8
Here is the traceback:
Traceback (most recent call last):
  File "/home/ljc/down/deepcpg-keras2/scripts/dcpg_train.py", line 832, in <module>
    app.run(sys.argv)
  File "/home/ljc/down/deepcpg-keras2/scripts/dcpg_train.py", line 194, in run
    return self.main(name, opts)
  File "/home/ljc/down/deepcpg-keras2/scripts/dcpg_train.py", line 802, in main
    verbose=0)
  File "/home/ljc/anaconda3/lib/python3.5/site-packages/Keras-2.0.8-py3.5.egg/keras/legacy/interfaces.py", line 87, in wrapper
  File "/home/ljc/anaconda3/lib/python3.5/site-packages/Keras-2.0.8-py3.5.egg/keras/engine/training.py", line 2082, in fit_generator
  File "/home/ljc/anaconda3/lib/python3.5/site-packages/Keras-2.0.8-py3.5.egg/keras/callbacks.py", line 77, in on_epoch_end
  File "/home/ljc/anaconda3/lib/python3.5/site-packages/Keras-2.0.8-py3.5.egg/keras/callbacks.py", line 751, in on_epoch_end
ValueError: If printing histograms, validation_data must be provided, and cannot be a generator.

**Comment by cangermueller** [comment]
I added a flag '--no_tensorboard' to `dcpg_traing.py` to disable Tensorboard summaries during training. Can you update your code (git pull) and check if it works when you are using `dcpg_train.py --no_tensorboard`?

**Comment by AgentLjc** [comment]
Thanks a lot! It works. However,what should i do if i want to use tensorboard ?Or what "validation_data" should i provide? Waiting for your reply!

**Comment by cangermueller** [comment]
I am about to fix this. Should be done until Wed.

**Comment by cangermueller** [comment]
Keras 2 is now the default Keras version. Please checkout the latest master branch and let me know if the problem still persists.

**Comment by AgentLjc** [comment]
Thanks for your jobs! However,the problem still persists unless I change the value of `histogram_freq` from 1 to 0 in `dcpg_train.py `.And there is a warning which may be related to this problem:
```
INFO (2017-11-20 18:56:34,479): Loading data ...
INFO (2017-11-20 18:56:34,481): Initializing callbacks ...
INFO (2017-11-20 18:56:34,481): Training model ...

Training samples: 1000
Validation samples: 1000
/home/ljc/anaconda3/lib/python3.5/site-packages/deepcpg-1.0.4-py3.5.egg/EGG-INFO/scripts
/dcpg_train.py:806: UserWarning: Update your 'fit_generator' call to the Keras 2 API: 
'fit_generator(<deepcpg.d..., workers=1, steps_per_epoch=7, callbacks=[<keras.ca..., verbose=0, 
epochs=1, max_queue_size=10, validation_steps=7, validation_data=<deepcpg.d...)'
```

**Comment by cangermueller** [comment]
@AgentLjc, you are using deepcpg-1.0.4, which does not support Keras 2. Either checkout the master branch from the DeepCpG repository, or update your version using `pip install -U deepcpg`.

**Comment by zao** [comment]
One of our users encountered this problem with DeepCpG 1.0.5, Python 3.6.1, Keras 2.0.8, Tensorflow/1.3.0. The same run with Theano/0.9.0 is fine, but way slower.

I don't have any conclusive speed results yet as their job is still running, but based on my tests, if I use Tensorflow, I _must_ use `--no_tensorboard` in order to get past the error the OP reported.

It would be nice if this was at least documented outside of this issue for anyone else that tries to use the Tensorflow backend of Keras.

**Comment by cangermueller** [comment]
If your Keras backend is not 'tensorflow', then Tensorboard is disabled in the same way as by using `--no_tensorboard`. I recommend using Tensorboard instead of Theano since Theano is dead.

**Comment by zao** [comment]
> I recommend using Tensorboard instead of Theano since Theano is dead.

Did you mean TensorFlow here?
I must admit that I'm not entirely up to speed with the backends and tools around this field, as I'm a cluster admin, not a user.

My understanding and concern is that if you use 'tensorflow' as the Keras backend, DeepCpG just won't work unless you supply the `--no_tensorboard` parameter.
Is there any scenario where that actually works and shouldn't just be automatically disabled? Is there any value to be gained from the TensorBoard functionality, or should the builtin output from DeepCpG be quite sufficient to do science with?

As it currently stands with DeepCpG 1.0.5, if the user or the site admin has configured the Keras backend to be TensorFlow, they're in for an automatic batch queue failure unless they happen to know to pass in `--no_tensorboard`.
