### ISSUE TITLE
Keras/Tensorflow combatible versions

### ISSUE THREAD

**Issue by eathieniti** [cangermueller/deepcpg#14]
Hi,
Could you please recommend a keras and tensorflow compatible versions? I am getting multiple issues with the latest versions.. eg. 

AttributeError: module 'keras.regularizers' has no attribute 'WeightRegularizer'

Thanks!

**Comment by AgentLjc** [comment]
download the Keras2 brach , ‘WeightRegularizer’ is used by Keras1

**Comment by cangermueller** [comment]
DeepCpG supports Keras>=2.0.2 and tensorflow>=1.0.1. I updated requirements.txt
