### ISSUE TITLE
No access to ./data/anno.zip on the server

### ISSUE THREAD

**Issue by JieYang031** [cangermueller/deepcpg#17]
Hi, I am trying to download the data using "bash setup.sh", but I cannot download the anno.zip because no permission to access. Could you please figure it out?

Thanks
jie

**Comment by cangermueller** [comment]
The file is currently unavailable. Download `anno.zip` from [here](https://drive.google.com/open?id=1rjQLshQZi1KdGSs-HUIB8vyPHOIYprkL)  and extract it manually to `data/annos`.
