### ISSUE TITLE
Cannot open the deep_cpg/notebooks/basics/index.ipynb

### ISSUE THREAD

**Issue by JieYang031** [cangermueller/deepcpg#18]
Hi, I cannot open the deep_cpg/notebooks/basics/index.ipynb file, Jupyter notebook return the error as : NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)

I also tried to run the sh data.sh from the example folder but I got the following errors:

> Traceback (most recent call last):
>   File "/Users/jyang32/anaconda3/bin/dcpg_data.py", line 4, in <module>
>     __import__('pkg_resources').run_script('deepcpg==1.0.6', 'dcpg_data.py')
>   File "/Users/jyang32/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/Users/jyang32/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1518, in run_script
>     .format(**locals()),
> pkg_resources.ResolutionError: Script 'scripts/dcpg_data.py' not found in metadata at '/Users/jyang32/anaconda3/lib/python3.6/site-packages/deepcpg-1.0.6.dist-info'

Could you provide some hints? Thank you!

All other scripts can work properly.

Jie

**Comment by cangermueller** [comment]
Hi Jie,

the notebook was indeed broken. I reset to an older version. Please checkout the latest version from github and try again.

Christof
