### ISSUE TITLE
erros and warnings

### ISSUE THREAD

**Issue by PoisonAlien** [cangermueller/deepcpg#22]
Hi,

Please accept my apologies if these questions are already answered some where in the docs or in  previous issues. 

1. I have scBS data from mice and I wanted to impute the matrix. I followed the steps to generate input data with `dcpg_data.py` and I received a ton of no cpg site warnings. Is it correct to assume that most of the warnings are due to non-directional library protocol (aligned to all 4 strands with bismark) ? Is there a way to mitigate the issue ?

2. Next, I wanted a [train](https://deepcpg.readthedocs.io/en/latest/train.html#train) a model, however I am getting the error 

```
dcpg_train.py  train_files \
    --val_files val_files \
    --dna_model CnnL2h128 --out_dir deepCpG/model/dna/ --nb_epoch 30

AttributeError: 'Model' object has no attribute 'input_layers'
```
train files and val files are generated as in the docs (splitting by chromosomes).

3. I then tried with the pre-compiled models, and I have the following error

```
$ dcpg_download.py Smallwood2014_2i_cpg -o deepCpG/model/Smallwood2014_2i_cpg

$ dcpg_train.py deepCpG/data/*.h5 --cpg_model deepCpG/model/Smallwood2014_2i_cpg/ --out_dir deepCpG/model/cpg/ --fine_tune

ValueError: Unknown layer: Merge
```
Am I missing something here ?

-Anand

**Comment by cangermueller** [comment]
Hi Anand,

The first problem (1.) is due to the non-directional library protocol as you pointed out. Positions in your input file must point to the 'C' of a 'CG' site.

The second problem (2.) is due to your Keras version. DeepCpG currently does not support  Keras > 2.1.4. Please try with Keras 2.1.4. I am about to migrate the code base to the most recent Keras version.

- Christof

**Comment by PoisonAlien** [comment]
Thanks Christof. I will give it a try.

**Comment by PoisonAlien** [comment]
Hi Christof,

1. I downgraded my Keras version to the supported version (2.1.4) and `dcpg_train.py` seems to be running (hasn't finished yet). 

I am also running with `Smallwood2014_2i_cpg` model but now I have following issue..

```
$dcpg_train.py deepCpG/data/*.h5 --cpg_model deepCpG/model/Smallwood2014_2i_cpg/ --out_dir deepCpG/model/cpg/ --fine_tune

ValueError: Improper config format: {u'l2': 9.999999747378752e-05, u'name': u'WeightRegularizer', u'l1': 0.0}

```
I see that you also had the same issue a while [back](https://github.com/keras-team/keras/issues/6382). Were you able to fix it ?  Or should I further downgrade my Keras version ?

2. And for model training, should I use all the samples (as I am doing now) or should it be run per cell-type ?

Thanks again.

**Comment by cangermueller** [comment]
Sorry for the late response: the message is because the Smallwood2014 model was trained with Keras 1 and can not be restored with Keras >2.0. I suggest to train models on your data from scratch.

**Comment by cangermueller** [comment]
I updated DeepCpG so support the most recent recent Keras version. I suggest to sync your deepcpg repository and use the most recent Keras version from now.
