### ISSUE TITLE
Error in train.sh

### ISSUE THREAD

**Issue by yasin-chop** [cangermueller/deepcpg#32]
_I am trying to run example data for training (train.sh) but getting the following error:
WARNING:tensorflow:From ~/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py:180: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING (2019-09-26 15:41:00,377): From ~/.local/lib/python2.7/site-packages/tensorflow/python/ops/nn_impl.py:180: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
INFO (2019-09-26 15:41:00,617): Loading data ...
INFO (2019-09-26 15:41:00,908): Initializing callbacks ...
Traceback (most recent call last):
  File "~/.local/bin/dcpg_train.py", line 836, in <module>
    app.run(sys.argv)
  File "~/.local/bin/dcpg_train.py", line 195, in run
    return self.main(name, opts)
  File "~/.local/bin/dcpg_train.py", line 790, in main
    callbacks = self.get_callbacks()
  File "~/.local/bin/dcpg_train.py", line 459, in get_callbacks
    if K._BACKEND == 'tensorflow' and not opts.no_tensorboard:
AttributeError: 'module' object has no attribute '_BACKEND'

Can you help what is this error about?_

**Comment by cangermueller** [comment]
Thanks for pointing this out. I removed the K._backend test. It should work once you synced to head.
