### ISSUE TITLE
can you provide datasets?

### ISSUE THREAD

**Issue by IamMegatron2025** [cangermueller/deepcpg#5]
hello, new to CpG,  I want to run `dcpg_data.py` to create the input data for DeepCpG, but I have no dataset like  `./cpg/cell[123].tsv` and `./dna/mm10`. so can you provide them or link?
thank you very much!!

**Comment by cangermueller** [comment]
Did you run `setup.py` as described [here](https://github.com/cangermueller/deepcpg/tree/master/examples) and did you try some of the example scripts or notebooks?

**Comment by IamMegatron2025** [comment]
@cangermueller thank you, now I see the example.

**Comment by IvyGongoogle** [comment]
@cangermueller did you see my question? I need your help.
