### ISSUE TITLE
confused on y and z in 'deepcpg/evaluate.py/evaluate(y, z, mask=CPG_NAN, metrics=CLA_METRICS)'

### ISSUE THREAD

**Issue by IamMegatron2025** [cangermueller/deepcpg#9]
hello, I am confused about the `evaluate` for `CLA_METRICS`. 
In the function ` deepcpg/evaluate.py/evaluate(y, z, mask=CPG_NAN, metrics=CLA_METRICS)`,  `y` seems to not correspond to z, so I can not understand the results of evaluate like acc.
can you explain this?

**Comment by cangermueller** [comment]
Throughout the code `y` are true labels and `z` model predictions.
